// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID        uuid.UUID
	Title     string
	Content   string
	AuthorID  uuid.UUID
	Photo     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	Surname   string
	Username  string
	Email     string
	Grade     int32
	Photo     string
	Verified  bool
	Password  string
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
